jobs:
  deploy-to-zhdk-leihs-test:
    include: cider-ci/task-components/deploy-defaults.yml
    name: Deploy to zhdk-leihs-test.ruby.zhdk.ch
    run_when:
      'on personal integration branch':
        type: branch
        include_match: ^([a-z]+_)?(next|master)$
        exclude_match: '^.*no-ci.*$'

    context:

      task_defaults:
        exclusive_global_resources:
          "zhdk-leihs-test.ruby.zhdk.ch": true
        environment_variables:
          DEPLOY_TARGET_INVENTORY: test-hosts

      tasks:
        deploy:
          include: cider-ci/task-components/zhdk-test-deploy.yml
