jobs:
  deploy-to-zhdk-leihs-test:
    include: cider-ci/task-components/deploy-defaults.yml
    name: Deploy to zhdk-leihs-test.ruby.zhdk.ch
    context:
    run_when:
      'on personal integration branch':
        type: branch
        include_match: ^[a-z]{2}_master$
        exclude_match: '^.*no-ci.*$'
    context:
      tasks:
        deploy:
          exclusive_global_resources:
            "zhdk-leihs-test.ruby.zhdk.ch": true
          scripts:
            deploy:
              timeout: 10 Minutes
              body: |
                set -eux
                cd deploy
                export ANSIBLE_HOST_KEY_CHECKING=False
                ansible-playbook deploy_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/test-hosts
