jobs:
  test-container-deploy:
    name: Test Deploy to a Container
    run_when:
      'on personal integration branch':
        type: branch
        include_match: ^[a-z]{2}_master$
        exclude_match: '^.*no-ci.*$'
    context:
      include:
        - path: container-test/cider-ci/context.yml
          submodule: [deploy]

      task:
        scripts:
          debug-ci:
            body: touch _cider-ci_keep
          deploy-to-container:
            start_when: {debug-ci: {script_key: debug-ci}}
          destroy-container: # skip it
            body: 'true'
